version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    container_name: kiosk_extra-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    container_name: kiosk_extra-web
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../:/var/www
    ports:
      - 7777:80
  db:
    image: mariadb:latest
    container_name: kiosk_extra-db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

volumes:
  dbdata: