<link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&amp;display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{$admin_source}}/plugins/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="{{$admin_source}}/fonts/Linearicons/Font/demo-files/demo.css">
<link rel="stylesheet" href="{{$admin_source}}/plugins/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="{{$admin_source}}/plugins/owl-carousel/assets/owl.carousel.css">
<link rel="stylesheet" href="{{$admin_source}}/plugins/select2/dist/css/select2.min.css">
<link rel="stylesheet" href="{{$admin_source}}/plugins/summernote/summernote-bs4.min.css">
<link rel="stylesheet" href="{{$admin_source}}/plugins/apexcharts-bundle/dist/apexcharts.css">
<link rel="stylesheet" href="{{$admin_source}}/css/style.css">